# Generated by Django 5.1.1 on 2024-10-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_alter_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
