# Generated by Django 5.1.1 on 2024-10-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0004_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
