# Generated by Django 5.1.1 on 2024-10-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0005_alter_question_question_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_code',
        ),
    ]
