# Generated by Django 5.1.1 on 2024-10-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0006_rename_question_answer_question_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
