# Generated by Django 5.1.1 on 2024-10-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0007_rename_answer_answer_answer_text_answer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
